-- =============================================================
-- V62 — Enrich template structures with complete vertical content
-- =============================================================

-- 1. Project Timeline — full waterfall structure
UPDATE project_templates SET structure_json = '{"phases":["Initiation","Planning","Execution","Monitoring & Control","Closure"],"statuses":["To Do","In Progress","Review","Done"],"tasks":{"Initiation":["Define project scope","Identify stakeholders","Create project charter","Kick-off meeting"],"Planning":["Create WBS","Define milestones","Resource allocation","Risk assessment","Communication plan"],"Execution":["Execute work packages","Team coordination","Status reporting","Quality assurance"],"Monitoring & Control":["Track progress","Variance analysis","Change management","Risk monitoring"],"Closure":["Final deliverables review","Lessons learned","Project sign-off","Archive documentation"]},"dependencies":[{"from":"Initiation","to":"Planning","type":"FS"},{"from":"Planning","to":"Execution","type":"FS"},{"from":"Execution","to":"Monitoring & Control","type":"SS"},{"from":"Execution","to":"Closure","type":"FS"}],"deliverables":["Project Charter","WBS Document","Status Reports","Final Report","Lessons Learned"]}',
capability_profile = '{"planning":true}' WHERE id = 'tpl-timeline';

-- 2. Project Tracking — progress and effort tracking
UPDATE project_templates SET structure_json = '{"phases":["Setup","Active","Review","Complete"],"statuses":["Backlog","To Do","In Progress","Testing","Done"],"tasks":{"Setup":["Configure project settings","Import initial backlog","Set up team members","Define priorities"],"Active":["Sprint/iteration planning","Daily standups","Work execution","Time logging","Blocker resolution"],"Review":["Sprint review","Velocity analysis","Effort variance report","Retrospective"],"Complete":["Final review","Archive","Metrics summary"]},"metrics":["completion_percentage","effort_variance","velocity","burn_rate"],"dashboardWidgets":["progress","blockers","velocity_chart","time_breakdown"]}',
capability_profile = '{"planning":true,"finance":true}' WHERE id = 'tpl-tracking';

-- 3. Gantt Project — full planning with WBS
UPDATE project_templates SET structure_json = '{"phases":["Phase 1 - Foundation","Phase 2 - Development","Phase 3 - Integration","Phase 4 - Delivery"],"statuses":["Not Started","In Progress","Completed","On Hold"],"wbs":[{"code":"1","name":"Foundation","children":[{"code":"1.1","name":"Requirements"},{"code":"1.2","name":"Design"},{"code":"1.3","name":"Approval"}]},{"code":"2","name":"Development","children":[{"code":"2.1","name":"Module A"},{"code":"2.2","name":"Module B"},{"code":"2.3","name":"Testing"}]},{"code":"3","name":"Integration","children":[{"code":"3.1","name":"System Integration"},{"code":"3.2","name":"UAT"},{"code":"3.3","name":"Bug Fixes"}]},{"code":"4","name":"Delivery","children":[{"code":"4.1","name":"Deployment"},{"code":"4.2","name":"Training"},{"code":"4.3","name":"Handover"}]}],"dependencies":[{"from":"1.1","to":"1.2","type":"FS"},{"from":"1.2","to":"1.3","type":"FS"},{"from":"1.3","to":"2.1","type":"FS"},{"from":"2.3","to":"3.1","type":"FS"},{"from":"3.3","to":"4.1","type":"FS"}],"baselineOnFirstSave":true}',
capability_profile = '{"planning":true}' WHERE id = 'tpl-gantt';

-- 4. Nonprofit Grant Project
UPDATE project_templates SET structure_json = '{"phases":["Application","Award","Implementation","Reporting","Closure"],"statuses":["Draft","Pending","Active","Under Review","Completed"],"tasks":{"Application":["Identify funding opportunity","Check eligibility","Prepare proposal","Budget preparation","Submit application"],"Award":["Award notification","Contract review","Set up reporting schedule","Kick-off with funder"],"Implementation":["Activity execution","Financial tracking","Evidence collection","Interim reporting","Beneficiary tracking"],"Reporting":["Prepare financial report","Prepare narrative report","Evidence compilation","Submit to funder","Funder review"],"Closure":["Final report","Audit preparation","Lessons learned","Archive"]},"budgetCategories":["PERSONNEL","TRAVEL","EQUIPMENT","SUPPLIES","SUBGRANTS","OVERHEAD","INDIRECT"],"deliverables":["Proposal","Award Letter","Interim Report","Financial Report","Final Report","Audit Report"],"reportingPeriods":["Q1","Q2","Q3","Q4","Annual"],"obligations":["Financial reporting","Narrative reporting","Audit","Evidence retention"]}',
capability_profile = '{"planning":true,"finance":true,"grants":true}' WHERE id = 'tpl-nonprofit';

-- 5. Public Call Application
UPDATE project_templates SET structure_json = '{"phases":["Discovery","Preparation","Submission","Evaluation","Award"],"statuses":["Identified","Evaluating","Preparing","Submitted","Awarded","Rejected"],"tasks":{"Discovery":["Scan funding opportunities","Initial eligibility check","Go/No-go decision"],"Preparation":["Detailed requirements analysis","Partner identification","Budget drafting","Technical proposal","Administrative documents","Internal review"],"Submission":["Final review","Package assembly","Electronic submission","Confirmation receipt"],"Evaluation":["Track evaluation timeline","Respond to clarifications","Site visit preparation"],"Award":["Contract negotiation","Project setup","Team mobilization"]},"eligibilityChecklist":["Legal status","Financial capacity","Technical capacity","Geographic eligibility","Thematic alignment","Partnership requirements","Budget limits"],"submissionDocuments":["Application form","Budget spreadsheet","Partnership agreements","CVs of key personnel","Past experience references","Legal documents"]}',
capability_profile = '{"grants":true}' WHERE id = 'tpl-publiccall';

-- 6. Sponsored Initiative
UPDATE project_templates SET structure_json = '{"phases":["Proposal","Agreement","Execution","Review","Close"],"statuses":["Draft","Proposed","Active","Under Review","Completed"],"tasks":{"Proposal":["Identify sponsor","Prepare pitch","Define deliverables","Budget estimate"],"Agreement":["Negotiate terms","Sign agreement","Set milestones","Communication plan"],"Execution":["Deliver milestones","Sponsor updates","Evidence collection","Financial tracking"],"Review":["Sponsor review meeting","Impact assessment","Satisfaction survey"],"Close":["Final report to sponsor","Recognition activities","Renewal discussion"]},"stakeholderMap":[{"role":"Sponsor","influence":"CRITICAL","interest":"HIGH"},{"role":"Project Lead","influence":"HIGH","interest":"HIGH"},{"role":"Beneficiaries","influence":"MEDIUM","interest":"HIGH"},{"role":"Board","influence":"HIGH","interest":"MEDIUM"}],"commitmentTypes":["Financial","In-Kind","Advisory","Networking"]}',
capability_profile = '{"finance":true,"grants":true}' WHERE id = 'tpl-sponsored';

-- 7. R&D Consortium
UPDATE project_templates SET structure_json = '{"phases":["WP0 - Management","WP1 - Research","WP2 - Development","WP3 - Validation","WP4 - Dissemination"],"statuses":["Not Started","In Progress","Deliverable Due","Completed"],"tasks":{"WP0 - Management":["Consortium coordination","Financial management","Reporting","Quality assurance","Risk management"],"WP1 - Research":["Literature review","Methodology design","Data collection","Analysis","Research deliverables"],"WP2 - Development":["Prototype design","Implementation","Testing","Documentation"],"WP3 - Validation":["Pilot setup","Pilot execution","Results analysis","Validation report"],"WP4 - Dissemination":["Publication plan","Conference papers","Project website","Final conference","Exploitation plan"]},"partners":["Coordinator","Research Partner 1","Research Partner 2","Industry Partner","SME Partner"],"deliverables":["D0.1 Management Plan","D1.1 Research Report","D2.1 Prototype","D3.1 Validation Report","D4.1 Dissemination Plan","D4.2 Final Report"],"coFundingModel":{"eu_contribution":70,"partner_contribution":30}}',
capability_profile = '{"planning":true,"finance":true,"grants":true,"portfolio":true}' WHERE id = 'tpl-consortium';

-- 8. Agency Delivery Project
UPDATE project_templates SET structure_json = '{"phases":["Discovery","Design","Build","Launch","Support"],"statuses":["Backlog","Sprint","In Review","Client Review","Done"],"tasks":{"Discovery":["Client briefing","Requirements gathering","Technical assessment","Proposal & SOW"],"Design":["UX research","Wireframes","Visual design","Design review","Client approval"],"Build":["Sprint planning","Development sprints","Code review","QA testing","Client demos"],"Launch":["Staging deployment","UAT","Go-live preparation","Production deployment","Post-launch monitoring"],"Support":["Bug fixes","Change requests","Monthly reporting","Handover documentation"]},"rateCards":["Senior Developer","Junior Developer","Designer","Project Manager","QA Engineer"],"budgetPerDeliverable":true,"timesheetRequired":true}',
capability_profile = '{"planning":true,"finance":true}' WHERE id = 'tpl-agency';

-- 9. Internal Operations Programme
UPDATE project_templates SET structure_json = '{"phases":["Planning","Execution","Review"],"statuses":["To Do","In Progress","Done","Deferred"],"tasks":{"Planning":["Quarterly OKR setting","Resource planning","Budget allocation","Risk assessment"],"Execution":["Initiative tracking","Weekly standups","Monthly reviews","KPI monitoring","Issue resolution"],"Review":["Quarterly review","Performance analysis","Lessons learned","Next quarter planning"]},"milestones":["Q1 Review","Q2 Review","Q3 Review","Q4 Review","Annual Review"],"operationalKPIs":["on_time_delivery","budget_adherence","team_utilization","stakeholder_satisfaction"]}',
capability_profile = '{"planning":true,"portfolio":true}' WHERE id = 'tpl-operations';

-- 10. Portfolio Review Workspace
UPDATE project_templates SET structure_json = '{"phases":["Setup","Active Monitoring","Review","Archive"],"statuses":["Active","Under Review","On Hold","Completed"],"dashboardWidgets":["portfolio_health","risk_concentration","funding_overview","resource_utilization","timeline_overview","budget_summary"],"reviewCadence":"monthly","aggregateMetrics":["total_budget","total_spent","projects_on_track","projects_at_risk","resource_utilization_pct"]}',
capability_profile = '{"portfolio":true}' WHERE id = 'tpl-portfolio';
